### ISSUE TITLE
How to improve nuclear segmentation and tracking

### ISSUE THREAD

**Issue by XiangruiJi** [computational-cell-analytics/micro-sam#1085]
Hi,

I'm trying to segment and track nuclei in embryos using the light microscopy (LM) model, but the performance is not ideal.

I draw a lasso prompt in the initial frame (using a point prompt segments the entire embryo), and select the "mask" projection (the "single_point" projection loses the nuclei even by the next frame).

<img width="1094" height="608" alt="Image" src="https://github.com/user-attachments/assets/536ff0c3-d63c-4517-87b1-0eaf84724896" />

However, after a few frames the mask no longer aligns with the nucleus.
<img width="1095" height="609" alt="Image" src="https://github.com/user-attachments/assets/142fe86e-b082-4abf-95fe-5f89f8fb05d9" />

Do you have any suggestions on how to improve the performance? Thanks!

**Comment by XiangruiJi** [comment]
Hi @anwai98 ,

I realized that my earlier issue was actually a path problem and I fixed it by changing the line for best_checkpoint to
best_checkpoint = os.path.join(root_dir, "models", "checkpoints", checkpoint_name, "best.pt")

However, I ran into another issue when trying the vit_l_lm model:

<img width="374" height="194" alt="Image" src="https://github.com/user-attachments/assets/56dea225-8902-4462-9dab-6b9920d9f857" />

<img width="865" height="65" alt="Image" src="https://github.com/user-attachments/assets/9a192e58-f0de-486e-944f-84c79b8ca8fa" />
...

<img width="865" height="15" alt="Image" src="https://github.com/user-attachments/assets/be06d9fb-3ae2-4662-9bb8-795758ec1110" />

Referring to [Running behind firewall. · Issue #1093 · computational-cell-analytics/micro-sam](https://github.com/computational-cell-analytics/micro-sam/issues/1093), I manually downloaded vit_l.pt from the provided link, renamed it as vit_l_lm, and moved it to the 'models' folder.

A similar error occurred when downloading the 'vit_l_lm_decoder' file.

<img width="865" height="33" alt="Image" src="https://github.com/user-attachments/assets/9d947c08-2682-4309-911a-27bc5c0a2720" />

I fixed this the same way. However, I noticed that the vit_l_decoder.pt file from the link is different from the one from [BioImage.IO - Model Zoo](https://bioimage.io/#/artifacts/idealistic-rat) (ViT-L) according to the file size.

<img width="865" height="20" alt="Image" src="https://github.com/user-attachments/assets/3576ffe8-0850-46e7-b05f-ba087294f62c" />
(from the link)


<img width="865" height="483" alt="Image" src="https://github.com/user-attachments/assets/2475e3a6-a12a-4a21-beb5-e68cb40b3c45" />
(from Model Zoo)

Which vit_l_decoder.pt file should I use? Thanks!

PS. Adding rectification points doesn't help much, so I plan to train my own model. As a first step, I am currently trying to run the example notebook.

**Comment by anwai98** [comment]
Well I spot another thing actually:

> `patch_shape=(73, 512, 512)`

`micro-sam` is an inherently 2d model (atleast at the training stage). This means, you need to train on 2d timepoints. You can simply switch to `(1, 512, 512)` as the patch shape and that should do the trick. But in any case, let me know if you can share the image and corresponding labels for me to test stuff!

**Comment by XiangruiJi** [comment]
Hi @anwai98 ,
Are there any updates on this training data loading issue? I can provide detailed error messages if needed. Thanks!

**Comment by anwai98** [comment]
Hi @XiangruiJi,

I realized I forgot to follow up on this. Sincere apologies for it.

Any updates on the progress from you side. Is the issue fixed by any chance?

**Comment by XiangruiJi** [comment]
Hi @anwai98 , I haven't made progress on it yet. I just updated my microsam to 1.7.7, but the data loading problem still exists. It would be great if you could help with this. I have emailed you my script, data and masks for training.

If ```raw_key, label_key= None, None```, ```raw_paths=image_paths```, ```label_paths=segmentation_paths``` are chosen, the error message is:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[5], line 28
     19 # NOTE: The dataloader internally takes care of adding label transforms: i.e. used to convert the ground-truth
     20 # labels to the desired instances for finetuning Segment Anythhing, or, to learn the foreground and distances
     21 # to the object centers and object boundaries for automatic segmentation.
   (...)
     24 # For this we use samplers, which ensure that valid inputs are chosen subjected to the paired labels.
     25 # The sampler chosen below makes sure that the chosen inputs have atleast one foreground instance, and filters out small objects.
     26 sampler = MinInstanceSampler(min_size=25)  # NOTE: The choice of 'min_size' value is paired with the same value in 'min_size' filter in 'label_transform'.
---> 28 train_loader = sam_training.default_sam_loader(
     29     # raw_paths=image_dir,
     30     raw_paths=image_paths,
     31     raw_key=raw_key,
     32     # label_paths=segmentation_dir,
     33     label_paths=segmentation_paths,
     34     label_key=label_key,
     35     with_segmentation_decoder=train_instance_segmentation,
     36     patch_shape=patch_shape,
     37     batch_size=batch_size,
     38     is_seg_dataset=True,
     39     rois=train_roi,
     40     shuffle=True,
     41     raw_transform=sam_training.identity,
     42     sampler=sampler,
     43 )
     45 val_loader = sam_training.default_sam_loader(
     46     # raw_paths=image_dir,
     47     raw_paths=image_paths,
   (...)
     59     sampler=sampler,
     60 )

File [~/.conda/envs/microsam/lib/python3.10/site-packages/micro_sam/training/training.py:796](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/micro_sam/training/training.py#line=795), in default_sam_loader(**kwargs)
    793 extra_ds_kwargs, loader_kwargs = split_kwargs(torch_em.default_segmentation_dataset, **extra_kwargs)
    794 ds_kwargs = {**sam_ds_kwargs, **extra_ds_kwargs}
--> 796 ds = default_sam_dataset(**ds_kwargs)
    797 return torch_em.segmentation.get_data_loader(ds, **loader_kwargs)

File [~/.conda/envs/microsam/lib/python3.10/site-packages/micro_sam/training/training.py:737](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/micro_sam/training/training.py#line=736), in default_sam_dataset(raw_paths, raw_key, label_paths, label_key, patch_shape, with_segmentation_decoder, with_channels, train_instance_segmentation_only, sampler, raw_transform, n_samples, is_train, min_size, max_sampling_attempts, rois, is_multi_tensor, **kwargs)
    735 # Set a minimum number of samples per epoch.
    736 if n_samples is None:
--> 737     loader = torch_em.default_segmentation_loader(
    738         raw_paths=raw_paths,
    739         raw_key=raw_key,
    740         label_paths=label_paths,
    741         label_key=label_key,
    742         batch_size=1,
    743         patch_shape=patch_shape,
    744         with_channels=with_channels,
    745         ndim=2,
    746         is_seg_dataset=is_seg_dataset,
    747         raw_transform=raw_transform,
    748         rois=rois,
    749         **kwargs
    750     )
    751     n_samples = max(len(loader), 100 if is_train else 5)
    753 dataset = torch_em.default_segmentation_dataset(
    754     raw_paths=raw_paths,
    755     raw_key=raw_key,
   (...)
    767     **kwargs,
    768 )

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/segmentation.py:268](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/segmentation.py#line=267), in default_segmentation_loader(raw_paths, raw_key, label_paths, label_key, batch_size, patch_shape, label_transform, label_transform2, raw_transform, transform, dtype, label_dtype, rois, n_samples, sampler, ndim, is_seg_dataset, with_channels, with_label_channels, verify_paths, with_padding, z_ext, **loader_kwargs)
    204 def default_segmentation_loader(
    205     raw_paths: Union[List[Any], str, os.PathLike],
    206     raw_key: Optional[str],
   (...)
    227     **loader_kwargs,
    228 ) -> torch.utils.data.DataLoader:
    229     """Get data loader for training a segmentation network.
    230 
    231     See `torch_em.data.SegmentationDataset` and `torch_em.data.ImageCollectionDataset` for details
   (...)
    266         The torch data loader.
    267     """
--> 268     ds = default_segmentation_dataset(
    269         raw_paths=raw_paths,
    270         raw_key=raw_key,
    271         label_paths=label_paths,
    272         label_key=label_key,
    273         patch_shape=patch_shape,
    274         label_transform=label_transform,
    275         label_transform2=label_transform2,
    276         raw_transform=raw_transform,
    277         transform=transform,
    278         dtype=dtype,
    279         label_dtype=label_dtype,
    280         rois=rois,
    281         n_samples=n_samples,
    282         sampler=sampler,
    283         ndim=ndim,
    284         is_seg_dataset=is_seg_dataset,
    285         with_channels=with_channels,
    286         with_label_channels=with_label_channels,
    287         with_padding=with_padding,
    288         z_ext=z_ext,
    289         verify_paths=verify_paths,
    290     )
    291     return get_data_loader(ds, batch_size=batch_size, **loader_kwargs)

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/segmentation.py:372](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/segmentation.py#line=371), in default_segmentation_dataset(raw_paths, raw_key, label_paths, label_key, patch_shape, label_transform, label_transform2, raw_transform, transform, dtype, label_dtype, rois, n_samples, sampler, ndim, is_seg_dataset, with_channels, with_label_channels, verify_paths, with_padding, z_ext)
    367     transform = _get_default_transform(
    368         raw_paths if isinstance(raw_paths, str) else raw_paths[0], raw_key, is_seg_dataset, ndim
    369     )
    371 if is_seg_dataset:
--> 372     ds = _load_segmentation_dataset(
    373         raw_paths,
    374         raw_key,
    375         label_paths,
    376         label_key,
    377         patch_shape=patch_shape,
    378         raw_transform=raw_transform,
    379         label_transform=label_transform,
    380         label_transform2=label_transform2,
    381         transform=transform,
    382         rois=rois,
    383         n_samples=n_samples,
    384         sampler=sampler,
    385         ndim=ndim,
    386         dtype=dtype,
    387         label_dtype=label_dtype,
    388         with_channels=with_channels,
    389         with_label_channels=with_label_channels,
    390         with_padding=with_padding,
    391         z_ext=z_ext,
    392     )
    394 else:
    395     ds = _load_image_collection_dataset(
    396         raw_paths,
    397         raw_key,
   (...)
    410         with_padding=with_padding,
    411     )

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/segmentation.py:113](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/segmentation.py#line=112), in _load_segmentation_dataset(raw_paths, raw_key, label_paths, label_key, **kwargs)
    111 assert len(raw_paths) > 0
    112 if rois is not None:
--> 113     assert len(rois) == len(label_paths)
    114     assert all(isinstance(roi, tuple) for roi in rois), f"{rois}"
    115 n_samples = kwargs.pop("n_samples", None)

AssertionError:
```

If ```raw_key, label_key = "*.tif", "*.tif"```, ```raw_paths=image_dir```, ```label_paths=segmentation_dir``` are chosen, the error message is:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[9], line 2
      1 # Run training
----> 2 sam_training.train_sam(
      3     name=checkpoint_name,
      4     save_root=os.path.join(root_dir, "models"),
      5     model_type=model_type,
      6     train_loader=train_loader,
      7     val_loader=val_loader,
      8     n_epochs=n_epochs,
      9     n_objects_per_batch=n_objects_per_batch,
     10     with_segmentation_decoder=train_instance_segmentation,
     11     device=device,
     12 )

File [~/.conda/envs/microsam/lib/python3.10/site-packages/micro_sam/training/training.py:279](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/micro_sam/training/training.py#line=278), in train_sam(name, model_type, train_loader, val_loader, n_epochs, early_stopping, n_objects_per_batch, checkpoint_path, with_segmentation_decoder, freeze, device, lr, n_sub_iteration, save_root, mask_prob, n_iterations, scheduler_class, scheduler_kwargs, save_every_kth_epoch, pbar_signals, optimizer_class, peft_kwargs, ignore_warnings, verify_n_labels_in_loader, box_distortion_factor, overwrite_training, strict_decoder_loading, **model_kwargs)
    277 t_start = time.time()
    278 if verify_n_labels_in_loader is not None:
--> 279     _check_loader(train_loader, with_segmentation_decoder, "train", verify_n_labels_in_loader)
    280     _check_loader(val_loader, with_segmentation_decoder, "val", verify_n_labels_in_loader)
    282 device = get_device(device)

File [~/.conda/envs/microsam/lib/python3.10/site-packages/micro_sam/training/training.py:41](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/micro_sam/training/training.py#line=40), in _check_loader(loader, with_segmentation_decoder, name, verify_n_labels_in_loader)
     40 def _check_loader(loader, with_segmentation_decoder, name=None, verify_n_labels_in_loader=None):
---> 41     x, _ = next(iter(loader))
     43     # Raw data: check that we have 1 or 3 channels.
     44     n_channels = x.shape[1]

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch/utils/data/dataloader.py:708](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch/utils/data/dataloader.py#line=707), in _BaseDataLoaderIter.__next__(self)
    705 if self._sampler_iter is None:
    706     # TODO(https://github.com/pytorch/pytorch/issues/76750)
    707     self._reset()  # type: ignore[call-arg]
--> 708 data = self._next_data()
    709 self._num_yielded += 1
    710 if (
    711     self._dataset_kind == _DatasetKind.Iterable
    712     and self._IterableDataset_len_called is not None
    713     and self._num_yielded > self._IterableDataset_len_called
    714 ):

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch/utils/data/dataloader.py:764](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch/utils/data/dataloader.py#line=763), in _SingleProcessDataLoaderIter._next_data(self)
    762 def _next_data(self):
    763     index = self._next_index()  # may raise StopIteration
--> 764     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
    765     if self._pin_memory:
    766         data = _utils.pin_memory.pin_memory(data, self._pin_memory_device)

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py:52](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py#line=51), in _MapDatasetFetcher.fetch(self, possibly_batched_index)
     50         data = self.dataset.__getitems__(possibly_batched_index)
     51     else:
---> 52         data = [self.dataset[idx] for idx in possibly_batched_index]
     53 else:
     54     data = self.dataset[possibly_batched_index]

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py:52](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py#line=51), in <listcomp>(.0)
     50         data = self.dataset.__getitems__(possibly_batched_index)
     51     else:
---> 52         data = [self.dataset[idx] for idx in possibly_batched_index]
     53 else:
     54     data = self.dataset[possibly_batched_index]

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/data/segmentation_dataset.py:217](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/data/segmentation_dataset.py#line=216), in SegmentationDataset.__getitem__(self, index)
    216 def __getitem__(self, index):
--> 217     raw, labels = self._get_sample(index)
    218     initial_label_dtype = labels.dtype
    220     if self.raw_transform is not None:

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/data/segmentation_dataset.py:193](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/data/segmentation_dataset.py#line=192), in SegmentationDataset._get_sample(self, index)
    191 # Padding the patch to match the expected input shape.
    192 if self.patch_shape is not None and self.with_padding:
--> 193     raw, labels = ensure_patch_shape(
    194         raw=raw,
    195         labels=labels,
    196         patch_shape=self.patch_shape,
    197         have_raw_channels=self._with_channels,
    198         have_label_channels=self._with_label_channels,
    199     )
    201 # squeeze the singleton spatial axis if we have a spatial shape that is larger by one than self._ndim
    202 if self.patch_shape is not None and len(self.patch_shape) == self._ndim + 1:

File [~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/util/util.py:245](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/torch_em/util/util.py#line=244), in ensure_patch_shape(raw, labels, patch_shape, have_raw_channels, have_label_channels, channel_first)
    242     else:
    243         pad_width = pw
--> 245     raw = np.pad(array=raw, pad_width=pad_width)
    247 # Extract the pad width and pad the label inputs
    248 if labels is not None and any(sh < psh for sh, psh in zip(labels_shape, patch_shape)):

File [~/.conda/envs/microsam/lib/python3.10/site-packages/numpy/lib/_arraypad_impl.py:757](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/numpy/lib/_arraypad_impl.py#line=756), in pad(array, pad_width, mode, **kwargs)
    754     raise TypeError('`pad_width` must be of integral type.')
    756 # Broadcast to shape (array.ndim, 2)
--> 757 pad_width = _as_pairs(pad_width, array.ndim, as_index=True)
    759 if callable(mode):
    760     # Old behavior: Use user-supplied function with np.apply_along_axis
    761     function = mode

File [~/.conda/envs/microsam/lib/python3.10/site-packages/numpy/lib/_arraypad_impl.py:534](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/numpy/lib/_arraypad_impl.py#line=533), in _as_pairs(x, ndim, as_index)
    530     raise ValueError("index can't contain negative values")
    532 # Converting the array with `tolist` seems to improve performance
    533 # when iterating and indexing the result (see usage in `pad`)
--> 534 return np.broadcast_to(x, (ndim, 2)).tolist()

File [~/.conda/envs/microsam/lib/python3.10/site-packages/numpy/lib/_stride_tricks_impl.py:410](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/numpy/lib/_stride_tricks_impl.py#line=409), in broadcast_to(array, shape, subok)
    367 @array_function_dispatch(_broadcast_to_dispatcher, module='numpy')
    368 def broadcast_to(array, shape, subok=False):
    369     """Broadcast an array to a new shape.
    370 
    371     Parameters
   (...)
    408            [1, 2, 3]])
    409     """
--> 410     return _broadcast_to(array, shape, subok=subok, readonly=True)

File [~/.conda/envs/microsam/lib/python3.10/site-packages/numpy/lib/_stride_tricks_impl.py:349](https://ondemand001.nemo.thecrick.org/node/ga110.nemo.thecrick.org/44379/lab/tree/home/users/jix/microSAM_finetuning/~/.conda/envs/microsam/lib/python3.10/site-packages/numpy/lib/_stride_tricks_impl.py#line=348), in _broadcast_to(array, shape, subok, readonly)
    346     raise ValueError('all elements of broadcast shape must be non-'
    347                      'negative')
    348 extras = []
--> 349 it = np.nditer(
    350     (array,), flags=['multi_index', 'refs_ok', 'zerosize_ok'] + extras,
    351     op_flags=['readonly'], itershape=shape, order='C')
    352 with it:
    353     # never really has writebackifcopy semantics
    354     broadcast = it.itviews[0]

ValueError: operands could not be broadcast together with remapped shapes [original->remapped]: (3,2)  and requested shape (4,2)
```

**Comment by anwai98** [comment]
Okay that's good to know. Then I can take care of scratching something up for you over the weekend. Thanks for getting back to me (with the data as well, thanks again).

I'll come back to you next week!

**Comment by anwai98** [comment]
Hi @XiangruiJi,

I managed to keep my promise this time and take a look at your data. I made some tiny changes to your dataloading scripts and pushed the scripts in this PR: https://github.com/computational-cell-analytics/micro-sam/pull/1209.

This should work fine. Let us know if you have any further questions (feel free to open a new PR for this). And thanks once again for your interest in `micro-sam`! 😁
